### ISSUE TITLE
Cannot change gradient color

### ISSUE THREAD

**Issue by duytran2610** [JSimonDev/rive_color_modifier#1]
I am unable to change the color of the stroke in the linear gradient that I have defined
<img width="443" alt="image" src="https://github.com/JSimonDev/rive_color_modifier/assets/147805900/fc2b739b-ba3b-412a-8988-9064dbedddde">

**Comment by JSimonDev** [comment]
Well thanks for opening the issue, soon I will be supporting gradients too 👾

**Comment by JSimonDev** [comment]
I’m going to close this issue since in version 2.1.1 gradients can now be changed. Thanks again for taking the time to open this issue; all feedback is welcome to improve the package.
