### ISSUE TITLE
Add Documentation Note on Exporting Names in Rive Files

### ISSUE THREAD

**Issue by behnamsattar** [JSimonDev/rive_color_modifier#3]
Hello,

I recently encountered an issue while using the package. It was unable to reference shapes and other elements by their names because these names were not being exported in the Rive files I was using. I discovered that in Rive, there is a specific setting that must be enabled to export these names along with the file.

I resolved this issue by enabling the "Export Options -> Export all names" setting in Rive, which allowed the package to function as intended. However, this requirement was not documented in the package's instructions, and it took a considerable amount of time to diagnose and resolve the issue.

Suggestion:
It would be highly beneficial for future users if the documentation could include a note or section about the need to enable the "Export names" setting in Rive when preparing files for use with this package. This addition would help prevent similar issues for others and improve the overall user experience.

Thank you for your efforts in maintaining this package. I look forward to seeing this enhancement in the documentation.

**Comment by JSimonDev** [comment]
Thank you for bringing this to my attention and for sharing your experience with the package. I appreciate your detailed explanation of the issue you encountered and the solution you found.
I am aware of this limitation in the current version of the package, and I want to assure you that I am working on addressing it. In the upcoming update, I will be making several improvements:

I will update the documentation to include a note about the "Export Options -> Export all names" setting in Rive. This will help future users avoid the issue you encountered and streamline their workflow.
Additionally, I'm planning to expand the package's capabilities by adding support for linear and radial gradients.

These enhancements will be part of the next release, which I aim to publish soon. Your feedback is invaluable in helping me improve the package and its usability for the community.
Thank you again for taking the time to report this issue and for your suggestion regarding the documentation. Your contribution is greatly appreciated :)
