### ISSUE TITLE
Remove Unnecessary Disposal of RenderObject in RiveColorModifier

### ISSUE THREAD

**Issue by behnamsattar** [JSimonDev/rive_color_modifier#4]
Hello,

I've encountered an issue with the RiveColorModifier widget in your package where the overridden didUnmountRenderObject method is causing framework exceptions. This method currently disposes of the RiveCustomRenderObject:

```dart
@override
void didUnmountRenderObject(covariant RiveCustomRenderObject renderObject) {
  renderObject.dispose();
}
```

The disposal of the render object when the RiveColorModifier is removed from the screen is leading to exceptions, specifically when navigating away from a screen or when the widget is otherwise disposed of by the framework.

This behavior differs from the original Rive widget, which this modifier is inspired by. Notably, the Rive widget does not override the didUnmountRenderObject method to dispose of its render object. Following the design of the original Rive widget seems more appropriate and aligns better with Flutter's lifecycle management for render objects.

Suggestion:
I recommend removing the override of the didUnmountRenderObject method in the RiveColorModifier or ensuring it aligns with the lifecycle management used in the original Rive package. This change should prevent the exceptions currently being thrown during widget disposal.

Thank you for looking into this issue. Adjusting this behavior will likely improve stability and compatibility with standard Flutter lifecycle practices.

**Comment by JSimonDev** [comment]
You're absolutely correct in your observation regarding the didUnmountRenderObject method in the RiveColorModifier widget causing framework exceptions. Your insight about the difference between my implementation and the original Rive widget is very valuable.
I agree with your suggestion to align the lifecycle management more closely with the original Rive package. This is indeed a more appropriate approach and should resolve the exceptions you're experiencing.
I will address this issue immediately and implement the necessary changes in the next release of the package. Your contribution to improving the stability and compatibility of this package is greatly appreciated.
If you have any further insights or encounter any other issues, please don't hesitate to let me know. I'm committed to maintaining a high-quality, stable package for the Flutter community.
Thank you once again for your detailed report and helpful suggestion.
